return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "actionlint",
      "ansible-language-server",
      "ansible-lint",
      "antlers-language-server",
      "black",
      "bash-language-server",
      "blade-formatter",
      "codelldb",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "dot-language-server",
      "emmet-ls",
      "eslint_d",
      "flake8",
      "gopls", -- Go language server
      "hadolint",
      "html-lsp",
      "intelephense", -- Added from the second config
      "nginx-language-server",
      "php-debug-adapter",
      "phpstan",
      "pint",
      "prettierd",
      "pyright",
      "rustywind",
      "shellcheck",
      "shfmt",
      "stylua",
      "tailwindcss-language-server",
    },
  },
}
